---
connections:
    -
        name: map
        token: MY_TOKEN
map:
    default: fake
    providers:
        -
            name: fake
            type: ../examples/fakeMapProvider
            connection: map
        -
            name: badFake
            type: ../examples/badFakeMapProvider
            connection: map