---
connections:
    -
        name: map
        token: MY_TOKEN
map:
    default: fake
    providers:
        -
            name: fake
            type: ~/spec/helpers/map/fakeProvider
            connection: map
        -
            name: badFake
            type: ~/spec/helpers/map/badFakeProvider
            connection: map
